name: Update GitHub Activity in README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update recent activity in README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          COMMIT_MSG: "chore: update recent GitHub activity"
          MAX_LINES: 6
